image: docker:stable

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: "git.sitesoft.ru:4567/$CI_PROJECT_PATH"
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl
  - export NOW_TIMESTAMP=$(date +'%Y%m%d%H%M%S')
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.sitesoft.ru:4567

test image building:
  stage: build
  except:
    - master
  script:
    - docker build --cache-from $CONTAINER_IMAGE:latest .

build and push image:
  stage: build
  only:
    - master
  script:
    - docker build --tag $CONTAINER_IMAGE:$NOW_TIMESTAMP --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$NOW_TIMESTAMP
    - docker push $CONTAINER_IMAGE:latest
