version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: 'redis:6-alpine'
    restart: on-failure
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: 'rediscommander/redis-commander:latest'
    restart: always
    environment:
      - 'REDIS_HOSTS=local:redis:6379,local:localhost:7000'
    ports:
      - 8079:8081
